#!/bin/sh
set -x
set -e
shift

publisher=${1%.*}
extension=${1#*.}
version=$2

curl -L https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${publisher}/vsextensions/$extension/$version/vspackage \
     > "/tmp/${1}-${2}.vsix"

vsix-add "/tmp/${1}-${2}.vsix"
