#!/bin/sh
set -e

extension="$(basename ${1%.vsix})"

mkdir -p /home/rust/.code-server/extensions \
         /tmp/vsix-add/

unzip "$1" 'extension/*' -d /tmp/vsix-add
mv /tmp/vsix-add/extension /home/rust/.code-server/extensions/${extension}
rm -r /tmp/vsix-add/


